### ISSUE TITLE
results page is empty any idea what i'm doing wrong ?

### ISSUE THREAD

**Issue by quasiperfect** [shuvroroy/filament-spatie-laravel-health#12]
thanks for your work

i have installed you package but the results page is empty any idea what i'm doing wrong ?

![Untitled](https://user-images.githubusercontent.com/287513/165771811-3f4ec5b8-fc95-465f-9fa8-3f6b371c9eba.jpg)

**Comment by shuvroroy** [comment]
@quasiperfect Please follow this documentation
https://spatie.be/docs/laravel-health/v1/introduction

**Comment by quasiperfect** [comment]
thanks i just needed to register the checks
