### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pmg_db.health_check_result_history_items' doesn't exist

### ISSUE THREAD

**Issue by ArtemBulavin** [shuvroroy/filament-spatie-laravel-health#13]
I installed the package and got an error SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pmg_db.health_check_result_history_items' doesn't exist

**Comment by shuvroroy** [comment]
@ArtemBulavin Please follow this instruction
https://spatie.be/docs/laravel-health/v1/installation-setup#content-running-the-checks-by-scheduling-a-command

**Comment by ArtemBulavin** [comment]
Please add this to your documentation.
