### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'celeb.health_check_result_history_items' doesn't exist

### ISSUE THREAD

**Issue by MaheKarim** [shuvroroy/filament-spatie-laravel-health#16]
After Installing  Your Plugin In My Filament v2.15.3 Admin Panel , In Application Health Page Showing This Error .
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'celeb.health_check_result_history_items' doesn't exist
```

**Comment by shuvroroy** [comment]
```
php artisan vendor:publish --tag="health-migrations"
php artisan migrate
```

**Comment by MaheKarim** [comment]
Now It's Okay But I have Question, Before installing your application should i have to install [spatie/laravel-health] ?

**Comment by shuvroroy** [comment]
No need install [spatie/laravel-health] package separately

**Comment by MaheKarim** [comment]
Okay Thank You Bro <3
