### ISSUE TITLE
Method make() not found

### ISSUE THREAD

**Issue by IhsanDevs** [shuvroroy/filament-spatie-laravel-health#38]
<img width="1439" alt="image" src="https://github.com/shuvroroy/filament-spatie-laravel-health/assets/66362682/ac4e63e2-a004-41e8-9e3a-dce2ce3984e5">

![image](https://github.com/shuvroroy/filament-spatie-laravel-health/assets/66362682/f4613402-638a-4e59-aba4-5fb49f6f61bb)

**Comment by shuvroroy** [comment]
Docs already fixed thanks for reporting
