### ISSUE TITLE
Problem with the blade view

### ISSUE THREAD

**Issue by mike1278** [shuvroroy/filament-spatie-laravel-health#49]
The error is 'Cannot redeclare backgroundColor()' 

I think you will need to extract the functions from the blade component, or can you try to declare as static functions.

This problem is presented using the following libraries:
- Laravel 10.43
- filament 3.2
- octane 2.3 with frankenphp

![Screenshot from 2024-03-02 18-31-04](https://github.com/shuvroroy/filament-spatie-laravel-health/assets/37571010/6c6d5096-5da8-4155-ae7d-32fea5a9fdd2)

**Comment by mTresk** [comment]
Same problem.
