### ISSUE TITLE
Duplicite use in HealthCheckResults.php

### ISSUE THREAD

**Issue by Splinter37** [shuvroroy/filament-spatie-laravel-health#61]
In version 2.3 is duplicite USE in HealthCheckResults.php

line 11 and 12 - FilamentSpatieLaravelHealthPlugin

![image](https://github.com/user-attachments/assets/58585269-28c5-482c-a20f-f371a9b52e62)

**Comment by shuvroroy** [comment]
Fixed in this release https://github.com/shuvroroy/filament-spatie-laravel-health/releases/tag/v2.3.1
